FROM node:24-bookworm-slim

WORKDIR /app

ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG NEXT_PUBLIC_PRIVY_SIGNER_ID
ARG NEXT_PUBLIC_PRIVY_SIGNER_POLICY_IDS
ARG NEXT_SERVER_ACTIONS_ENCRYPTION_KEY

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_PRIVY_APP_ID=$NEXT_PUBLIC_PRIVY_APP_ID
ENV NEXT_PUBLIC_PRIVY_SIGNER_ID=$NEXT_PUBLIC_PRIVY_SIGNER_ID
ENV NEXT_PUBLIC_PRIVY_SIGNER_POLICY_IDS=$NEXT_PUBLIC_PRIVY_SIGNER_POLICY_IDS

COPY package.json package-lock.json .npmrc ./
RUN npm ci

COPY . .
RUN npm run build && npm run web:build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "web:start"]
