import "dotenv/config";

import { appendFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { createPublicClient, createWalletClient, formatUnits, http } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
// @ts-expect-error solc ships no types; script-only dependency.
import solc from "solc";

import { CircleWalletAdapter } from "../packages/adapters/circle/index.ts";
import {
  ARC_TESTNET_DEFAULT_RPC_URL,
  arcTestnet,
} from "../packages/adapters/arc/registry.ts";

// Compiles and deploys CassieTradeRegistry to Arc testnet.
// Usage: npx tsx scripts/deploy-trade-registry.ts
//
// Generates the operator key on first run (appended to .env), tops it up
// with gas from the Circle treasury when it's dry (USDC is Arc's native gas
// token), deploys, and appends the contract address to .env.

const envPath = join(process.cwd(), ".env");
const rpcUrl = process.env.CASSIE_ARC_RPC_URL ?? ARC_TESTNET_DEFAULT_RPC_URL;
const chain = arcTestnet(rpcUrl);

// ── operator key ────────────────────────────────────────────────
let operatorKey = process.env.CASSIE_ARC_OPERATOR_KEY as `0x${string}` | undefined;
if (!operatorKey) {
  operatorKey = generatePrivateKey();
  appendFileSync(
    envPath,
    `\n# Arc trade registry operator (generated by deploy-trade-registry.ts)\nCASSIE_ARC_OPERATOR_KEY=${operatorKey}\n`,
  );
  console.log("generated operator key and appended it to .env");
}
const operator = privateKeyToAccount(operatorKey);
console.log(`operator: ${operator.address}`);

// ── gas (native USDC) ───────────────────────────────────────────
const publicClient = createPublicClient({ chain, transport: http(rpcUrl) });
let balance = await publicClient.getBalance({ address: operator.address });
console.log(`operator gas balance: ${formatUnits(balance, 6)} USDC`);
if (balance < 500_000n) {
  console.log("funding operator with $2 gas from the treasury…");
  const transfer = await new CircleWalletAdapter().refundUserUsdcFromTreasury({
    userWalletAddress: operator.address,
    amountUsd: 2,
    referenceId: `arc-operator-gas:${Date.now()}`,
    chain: "arc",
  });
  console.log(`treasury transfer ${transfer.transferId}: ${transfer.status}`);
  for (let i = 0; i < 20 && balance < 500_000n; i += 1) {
    await new Promise((resolve) => setTimeout(resolve, 3000));
    balance = await publicClient.getBalance({ address: operator.address });
  }
  console.log(`operator gas balance: ${formatUnits(balance, 6)} USDC`);
  if (balance < 500_000n) throw new Error("Operator gas never arrived.");
}

// ── compile ─────────────────────────────────────────────────────
const source = readFileSync(
  join(process.cwd(), "contracts/CassieTradeRegistry.sol"),
  "utf8",
);
const compiled = JSON.parse(
  solc.compile(
    JSON.stringify({
      language: "Solidity",
      sources: { "CassieTradeRegistry.sol": { content: source } },
      settings: {
        optimizer: { enabled: true, runs: 200 },
        outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
      },
    }),
  ),
);
const errors = (compiled.errors ?? []).filter(
  (entry: { severity: string }) => entry.severity === "error",
);
if (errors.length > 0) {
  throw new Error(errors.map((entry: { formattedMessage: string }) => entry.formattedMessage).join("\n"));
}
const artifact = compiled.contracts["CassieTradeRegistry.sol"].CassieTradeRegistry;
const bytecode = `0x${artifact.evm.bytecode.object}` as `0x${string}`;
console.log(`compiled: ${bytecode.length / 2 - 1} bytes`);

// ── deploy ──────────────────────────────────────────────────────
if (process.env.CASSIE_ARC_REGISTRY_ADDRESS) {
  console.log(`registry already deployed at ${process.env.CASSIE_ARC_REGISTRY_ADDRESS} — nothing to do`);
  process.exit(0);
}
const wallet = createWalletClient({ account: operator, chain, transport: http(rpcUrl) });
const deployHash = await wallet.deployContract({
  // The solc artifact carries the constructor; the shared ABI only lists the
  // runtime functions the worker calls.
  abi: artifact.abi,
  bytecode,
  // Zero address → the deployer (our operator key) becomes the operator.
  args: ["0x0000000000000000000000000000000000000000"],
});
console.log(`deploy tx: ${deployHash}`);
const receipt = await publicClient.waitForTransactionReceipt({ hash: deployHash });
if (receipt.status !== "success" || !receipt.contractAddress) {
  throw new Error(`Deployment failed: ${receipt.status}`);
}
appendFileSync(envPath, `CASSIE_ARC_REGISTRY_ADDRESS=${receipt.contractAddress}\n`);
console.log(`CassieTradeRegistry deployed at ${receipt.contractAddress}`);
console.log(`explorer: https://testnet.arcscan.app/address/${receipt.contractAddress}`);
console.log("address appended to .env as CASSIE_ARC_REGISTRY_ADDRESS");
process.exit(0);
